#pragma once

#include <functional>
#include <list>
#include <map>
#include <optional>
#include <unordered_map>
#include <vector>

#include "order.hpp"

namespace matchengine {

// A single-symbol limit order book with price-time priority matching.
//
// Design notes:
//  - Bids are kept highest-price-first, asks lowest-price-first, so the
//    best price on each side is always begin() of its map.
//  - Each price level is a std::list<Order> in FIFO order, giving O(1)
//    push_back for new resting orders and stable iterators for cancel.
//  - An index (order_id -> location) gives O(log P) cancel by price level
//    lookup + O(1) list erase, instead of O(N) scanning the whole book.
//  - This class itself is NOT thread-safe by design: real matching engines
//    run the book on a single thread and push work onto it through a
//    lock-free queue (see include/spsc_queue.hpp + MatchingEngine), so the
//    hot path here never has to take a lock.
class OrderBook {
public:
    explicit OrderBook(std::string symbol) : symbol_(std::move(symbol)) {}

    // Submits a new limit order. Matches immediately against the opposite
    // side while prices cross; any unfilled remainder rests on the book.
    // Returns the trades generated by this call (may be empty).
    std::vector<Trade> add_limit_order(Order order);

    // Cancels a resting order by id. Returns true if found and removed.
    bool cancel_order(OrderId id);

    std::optional<PriceTicks> best_bid() const;
    std::optional<PriceTicks> best_ask() const;

    size_t bid_levels() const { return bids_.size(); }
    size_t ask_levels() const { return asks_.size(); }
    size_t open_order_count() const { return index_.size(); }

    const std::string& symbol() const { return symbol_; }

private:
    struct Location {
        Side side;
        PriceTicks price;
        std::list<Order>::iterator it;
    };

    template <typename Book, typename ShouldMatch>
    void match_against(Order& incoming, Book& opposite_book,
                        ShouldMatch should_match, std::vector<Trade>& trades);

    std::string symbol_;

    // Bids: highest price first. Asks: lowest price first (default less<>).
    std::map<PriceTicks, std::list<Order>, std::greater<PriceTicks>> bids_;
    std::map<PriceTicks, std::list<Order>> asks_;

    std::unordered_map<OrderId, Location> index_;
};

} // namespace matchengine
